ankaraonlinestore/ankaraonlinestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ankaraonlinestore/blog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name = 'post_list'),
    #path('blog/<tag_slug>/', views.post_list, name = 'post_list_by_tag'),
    url(r'^tags/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    path('post/<int:pk>/', views.post_detail, name = 'post_detail')
]

ankaraonlinestore/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ankaraonlinestore/shop/urls.py
from django.conf.urls import url
from django.urls import include, path
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    path('aboutus/', views.aboutus, name = 'aboutus'),
    path('contactus/', views.contactus, name = 'contactus'),
    path('privacypolicy', views.privacypolicy, name = 'privacypolicy'),
    path('shop/', views.product_list, name='product_list'),
    #path('shop/<category_slug>/', views.product_list, name = 'product_list_by_category'),
    url(r'^shop/categories/(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^shop/types/(?P<type_slug>[-\w]+)/$', views.product_list, name='product_list_by_type'),
    #path('shop/<type_slug>/', views.product_list, name='product_list_by_type'),
    url(r'^shop/brands/(?P<brand_slug>[-\w]+)/$', views.product_list, name='product_list_by_brand'),
    #path('shop/<brand_slug>/', views.product_list, name = 'product_list_by_brand'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

ankaraonlinestore/shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length = 150, db_index = True)
    slug = models.SlugField(max_length = 150, db_index = True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Type(models.Model):
    name = models.CharField(max_length = 150, db_index = True)
    slug = models.SlugField(max_length = 150, db_index = True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'type'
        verbose_name_plural = 'types'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_type', args=[self.slug])

class Brand(models.Model):
    name = models.CharField(max_length = 150, db_index = True)
    slug = models.SlugField(max_length = 150, db_index = True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_brand', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    type = models.ForeignKey(Type, related_name='products', on_delete = models.CASCADE, null= True)
    brand = models.ForeignKey(Brand, related_name='products', on_delete = models.CASCADE, null= True)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

ankaraonlinestore/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Type, Brand
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views import generic


def index(request): 
    return render(request, 'shop/product/index.html')
    
def aboutus(request):
    return render(request, 'shop/product/aboutus.html')

def contactus(request):
    return render(request, 'shop/product/contactus.html')

def privacypolicy(request):
    return render(request, 'shop/product/privacypolicy.html')

#Dynamic Page Views Start Here

def product_list(request, category_slug=None, type_slug = None, brand_slug = None):
    category = None
    categories = Category.objects.all()
    type = None
    types = Type.objects.all()
    brand = None
    brands = Brand.objects.all()

    products = Product.objects.filter(available=True)

    
    

    

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    if type_slug:
        type = get_object_or_404(Type, slug = type_slug)
        products = Product.objects.filter(type=type)
    
    if brand_slug:
        brand = get_object_or_404(Brand, slug = brand_slug)
        products = Product.objects.filter(brand = brand)
    
    paginator = Paginator(products, 8)
    
    page = request.GET.get('page')
 
    try:
        # create Page object for the given page
        products = paginator.page(page)
    except PageNotAnInteger:
        # if page parameter in the query string is not available, return the first page
        products = paginator.page(1)
    except EmptyPage:
        # if the value of the page parameter exceeds num_pages then return the last page
        products = paginator.page(paginator.num_pages)
    
    
    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'brand': brand,
        'brands':brands,
        'type': type,
        'types': types,
        
        'products': products
    })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

ankaraonlinestore/shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}On-line Shop{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/css/all.css' %}">
	<link rel="stylesheet" href="{% static 'css/css/brands.css' %}">
	<link rel="stylesheet" href="{% static 'css/css/solid.css' %}">
	<link rel="stylesheet" href="{% static 'css/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'img/logo/tablogo.jpg' %}">


    <style>
      .context-dark, .bg-gray-dark, .bg-primary {
    color: rgba(255, 255, 255, 0.8);
}

.footer-classic a, .footer-classic a:focus, .footer-classic a:active {
    color: #ffffff;
}
.nav-list li {
    padding-top: 5px;
    padding-bottom: 5px;
}

.nav-list li a:hover:before {
    margin-left: 0;
    opacity: 1;
    visibility: visible;
}

ul, ol {
    list-style: none;
    padding: 0;
    margin: 0;
}

.social-inner {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    padding: 23px;
    font: 900 13px/1 "Lato", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    text-transform: uppercase;
    color: rgba(255, 255, 255, 0.5);
}
.social-container .col {
    border: 1px solid rgba(255, 255, 255, 0.1);
}
.nav-list li a:before {
    content: "\f14f";
    font: 400 21px/1 "Material Design Icons";
    color: #4d6de6;
    display: inline-block;
    vertical-align: baseline;
    margin-left: -28px;
    margin-right: 7px;
    opacity: 0;
    visibility: hidden;
    transition: .22s ease;
}
    </style>


</head>
<body>

    


        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2">
                    <img src="{% static 'img/logo/logo.jpg' %}" class="header-logo">

                </div>
                <div class="col-md-8 tagline">
                    <p>Africa's Best Fabric Dealer...Your one stop shop for everything Ankara and More...</p>
                </div>


               

                
                

            </div>
            
        </div>

        
{% include 'shop/navbar.html' %}





<div class="content"> 
{% block content %}


{% endblock %}
</div>


    <footer class="section footer-classic context-dark bg-image" style="background:black;">
        <div class="container">
          <div class="row row-30">
            <div class="col-md-4 col-xl-5">
              <div class="pr-xl-4"><a class="brand" href="{% url 'shop:index' %}"><img class="brand-logo-light" src="{% static 'img/logo/tablogo.jpg' %}" style="height : 50px; width:50px;"></a>
                <p class="text-justify">We are Africa's Premier Ankara Fabrics Supplier. Whether it is a dress for birthday party or wedding, or asoebi for a group; we supply in Retail and Wholesale quantities</p>
                <!-- Rights-->
                <p class="rights"><span>©  </span><span class="copyright-year">2019</span><span> </span><span>Ankara Fabrics and More</span><span> | </span><span>All Rights Reserved.</span></p>
                <p><a style="color:white" href="https://ebhota.github.io/">Designed and Developed by  Papijo.</a></p>
              </div>
            </div>
            <div class="col-md-4">
              <h5>Company Information</h5>
              <dl class="contact-list">
                <dt>Address:</dt>
                <dd>Accra</dd>
              </dl>
              <dl class="contact-list">
                <dt>Email:</dt>
                <dd><a href="mailto:ankaraclothingandmore@gmail.com">ankaraclothingandmore@gmail.com </a></dd>
              </dl>
              <dl class="contact-list">
                <dt>Phone:</dt>
                <dd><a href="tel:+233 54 541 8699">+233 54 541 8699</a> <span>or</span> <a href="tel:+233 54 541 8699">+233 54 541 8699</a>
                </dd>
              </dl>
            </div>
            <div class="col-md-4 col-xl-3">
              <h5>Site Links</h5>
              <ul class="nav-list">
                <li><a href="{% url 'shop:aboutus' %}">About Us</a></li>
                <li><a href="{% url 'shop:product_list' %}">Shop</a></li>
                <li><a href="{% url 'blog:post_list' %}">Blog</a></li>
                <li><a href="{% url 'shop:contactus' %}">Contact Us</a></li>
                <li><a href="{% url 'shop:privacypolicy' %}">Privacy Policy</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row no-gutters social-container">
          <div class="col"><a class="social-inner" href="http://www.facebook.com/Ankarafabricsandmore/"><span class="icon mdi mdi-facebook"></span><span>Facebook</span></a></div>
          <div class="col"><a class="social-inner" href="http://www.instagram.com/ankarafabrics_and_more/"><span class="icon mdi mdi-instagram"></span><span>instagram</span></a></div>
          <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-twitter"></span><span>twitter</span></a></div>
          <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-youtube-play"></span><span>google</span></a></div>
        </div>
      </footer>



<script src="{% static 'js/jquery-3.3.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/main.js' %}" type = "text/javascript"></script>
</body>
</html>

ankaraonlinestore/shop/templates/shop/navbar.html
{% load static %}

<!--TopNav-->

<div class="topnav" id="myTopnav">
        <a href="{% url 'shop:index' %}" id="home"><i class="fas fa-home"></i> Home</a>
        <a href="{% url 'shop:product_list' %}" id="ourStock"><i class="fas fa-shopping-basket"></i> Our Shop</a>
       
        <a href="{% url 'blog:post_list' %}" id="blog"><i class = "fas fa-book"></i> Blog</a>

        <a href="{% url 'shop:contactus' %}" id="contact"><i class="fas fa-phone"></i> Contact Us</a>
        <a href="{% url 'shop:aboutus' %}" id="about"><i class="fas fa-users"></i> About Us</a>
        
        
        
        
        
        <a href="{% url 'cart:cart_detail' %}" id="shoppingCart"><i class="fas fa-shopping-cart"></i>
            {% with totail_items=cart|length %}
            {% if cart|length > 0 %}
                
                
                :
                    {{ totail_items }} item{{ totail_items|pluralize }}, Ghc. {{ cart.get_total_price }}
                
                {% else %}
                 Your cart is empty.
            {% endif %}
            {% endwith %}
        </a>
      
        
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
        </a>
    </div>
  <!--End of Top Nav-->