ankaraonlinestore/ankaraonlinestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ankaraonlinestore/blog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name = 'post_list'),
    #path('blog/<tag_slug>/', views.post_list, name = 'post_list_by_tag'),
    url(r'^tags/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    path('post/<int:pk>/', views.post_detail, name = 'post_detail')
]

ankaraonlinestore/blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse




class Tag(models.Model):
    name = models.CharField(max_length = 150, db_index = True)
    slug = models.SlugField(max_length = 150, db_index = True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    

    class Meta:
        ordering = ('name', )
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('blog:post_list_by_tag', args=[self.slug])






class Post(models.Model):
    title = models.CharField(max_length = 200)
    author = models.CharField(max_length = 200, null = True)
    tag = models.ForeignKey(Tag, related_name='posts', on_delete = models.CASCADE, null = True)
    summary = models.CharField(max_length = 200, null = True)
    text= models.TextField()
    created_date = models.DateTimeField(default = timezone.now)
    published_date= models.DateTimeField(blank = True, null = True)
    image = models.ImageField(upload_to='blog/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.title

    def get_tag_list(self):
        return (self.tag)

    class Meta:
        ordering = ["-published_date"]

ankaraonlinestore/blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post, Tag 
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

def post_list(request, tag_slug=None):

    tag = None
    tags = Tag.objects.all()

    post = None
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.objects.filter(tag=tag)

    

    paginator = Paginator(posts, 4)
 
    # get the page parameter from the query string
    # if page parameter is available get() method will return empty string ''
    page = request.GET.get('page')
 
    try:
        # create Page object for the given page
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page parameter in the query string is not available, return the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if the value of the page parameter exceeds num_pages then return the last page
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html', {
        'posts': posts,
        'tag': tag,
        'tags': tags
    })
    


def post_detail(request, pk):
    post = get_object_or_404(Post, pk = pk)
    return render(request, 'blog/post_detail.html', {'post': post})

ankaraonlinestore/blog/templates/blog/post_detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Ankara Blog  Detail
{% endblock %}

{% block content %}
<div class="jumbotron">
        <h1 class="text-center">Our Blog</h1>
</div>
        <div class= "container-fluid">
            <div class="row">
                <div class="col-md-2">
                        <div>
                                <img src="{% static 'img/sell3.jpg' %}" class="img-thumbnail" >
                          </div>

                </div>
                <div class="col-md-8">
                        <h2 class="text-center">{{post.title}}</h2>
                        <p class="text-center"><i>by {{post.author}}</i> </p>
                        <p><i> Posted on {{post.published_date}} </i> </p>
                        <p class="text-justify">{{post.text}}</p>
                        
                        <img class="rounded " src="{% if post.image %} {{ post.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 200px; width: 200px;">

                          
                        

                </div>
                <div class="col-md-2">
                        <div>
                                <img src="{% static 'img/sell1.jpg' %}" class="img-thumbnail" >
                          </div>

                </div>

            </div> 
        </div>
                <br>
                <br>
{% endblock %}

ankaraonlinestore/blog/templates/blog/post_list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Ankara Blog
{% endblock %}

{% block content %}
<div class="jumbotron">
        <h1 class="NTpagesContent text-center">Ankara Fabrics and More Blog</h1>
        
</div>

<div class="container-fluid">          
                        <div class="row">
                            <div class="col-md-2 leftSideBar">
                                    <h4><i class="fas fa-list-alt categorySidebar"></i> Tags</h4>
                                    
                                    <ol class="list-unstyled">
                                            <li {% if not tag %} class="active"{% endif %}><a class="categoryList categorySidebar" href="{% url 'blog:post_list' %}">All</a></li>
                                          
                                            {% for t in tags %}

                                            <li {% if tag.slug == t.slug %} class="active"{% endif %}>
                                                <a class="categoryList categorySidebar" href="{{ t.get_absolute_url }}">{{ t.name }}</a>
                                            </li>
                                          {% endfor %}
                                          </ol>
                                          <br>
                                          <div>
                                                <img src="{% static 'img/sell1.jpg' %}" class="img-thumbnail" >
                                          </div>

                                   

                            </div>
                            
                            <div class="col-md-8 mainBlog">
                                    <h4 class="blogJumbo2 text-center"> <b>Everything you need to know and more....</b></h4>
                                    
                                    <p>Blog List Page: Page {{ posts.number }} of {{ posts.paginator.num_pages }}</p>
                                    
                                        <div class="row">
                                                {% for post in posts %}
                                            <div class="col-md-3 text-center">
                                                

                                                    <br>
                                                    <a style="color:black;" href="{% url 'blog:post_detail' pk=post.pk %} ">
                                                        <img class="rounded" src="{% if post.image %} {{ post.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 175px; width: 100%">
                                                        <h3>{{post.title}} </h3>
                                                    </a>
                                                        <p>{{ post.summary }}</p> 
                                                        <p>Published: {{ post.published_date }}</p>
                                                    
                                                    
                                            </div>
                                            {% endfor %}  
                                           
                                            
                                        </div> 
                                        
                                       
                                        <nav aria-label="Page navigation example">
                                            <ul class="pagination justify-content-end">
                                              <li class="page-item">
                                                    {% if posts.has_previous %}
                                                <a class="page-link" href="?page={{ posts.previous_page_number }}" tabindex="-1">Previous</a>
                                                    {% endif %}
                                            </li>
                                            
                                            
                                            
                                            <li class="page-item">
                                                    {% if posts.has_next %}
                                                <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
                                                    {% endif %}
                                              </li>
                                            </ul>
                                          </nav>
                                          

                           </div>
                           

                           <div class="col-md-2 rightSidebar">
                               

                                <div>
                                        <img src="{% static 'img/sell3.jpg' %}" class="img-thumbnail"" >
                                  </div>

                           </div>
 
                        
                        
                        </div> <!--end of row-->

                    
                    
</div>               
{% endblock %}