ankaraonlinestore/ankaraonlinestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ankaraonlinestore/blog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name = 'post_list'),
    #path('blog/<tag_slug>/', views.post_list, name = 'post_list_by_tag'),
    url(r'^tags/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    path('post/<int:pk>/', views.post_detail, name = 'post_detail')
]

ankaraonlinestore/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ankaraonlinestore/orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create')
]

ankaraonlinestore/shop/urls.py
from django.conf.urls import url
from django.urls import include, path
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    path('aboutus/', views.aboutus, name = 'aboutus'),
    path('contactus/', views.contactus, name = 'contactus'),
    path('privacypolicy', views.privacypolicy, name = 'privacypolicy'),
    path('shop/', views.product_list, name='product_list'),
    #path('shop/<category_slug>/', views.product_list, name = 'product_list_by_category'),
    url(r'^shop/categories/(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^shop/types/(?P<type_slug>[-\w]+)/$', views.product_list, name='product_list_by_type'),
    #path('shop/<type_slug>/', views.product_list, name='product_list_by_type'),
    url(r'^shop/brands/(?P<brand_slug>[-\w]+)/$', views.product_list, name='product_list_by_brand'),
    #path('shop/<brand_slug>/', views.product_list, name = 'product_list_by_brand'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

ankaraonlinestore/cart/models.py
from django.db import models

# Create your models here.

ankaraonlinestore/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

ankaraonlinestore/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

ankaraonlinestore/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="row" style="margin-top: 6%; color:#9f1d35">
        <p class="shoppingCartHeader">
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        Shopping Order:
                        <a href="{% url 'cart:cart_detail' %}" style="color:#9f1d35">
                            {{ totail_items }} item{{ totail_items|pluralize }}, Ghc. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </p>

        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead style="background-color: #9f1d35; color:#FFA987">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove Item</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr style="background-color:#FFA987; color:#9f1d35; font-weight: bold;">
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img class="rounded" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-outline-dark">
                                </form>
                            </td>
                            <td>
                                <a class="btn btn-outline-dark" href="{% url 'cart:cart_remove' product.id %}">Remove</a>
                            </td>
                            <td>Ghc. {{ item.price }}</td>
                            <td>Ghc. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color:#9f1d35; color:#FFA987">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>Ghc. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        </div>
        
            <a href="{% url 'shop:product_list' %}" class="btn btn-default" style="color:#9f1d35; font-style:italic;"><i class="fas fa-shopping-basket"></i> Continue Shopping</a>
            <a href="{% url 'orders:order_create' %}" class="btn btn-default" style="color:#9f1d35; font-style:italic;"><i class="fas fa-shopping-cart"></i> Checkout</a>
        
        </div>
    </div>
{% endblock %}